name: Release
on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      PGP_PASSPHRASE: ${{ secrets.AUTOMATED_MAVEN_RELEASE_PGP_PASSPHRASE }}
      SONATYPE_USERNAME: guardian.automated.maven.release
      SONATYPE_PASSWORD: ${{ secrets.AUTOMATED_MAVEN_RELEASE_SONATYPE_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
          cache: sbt
          gpg-private-key: ${{ secrets.AUTOMATED_MAVEN_RELEASE_PGP_SECRET }}
          gpg-passphrase: PGP_PASSPHRASE
      - run: git config user.email "automated.maven.release.noreply@theguardian.com"
      - run: git config user.name "Guardian Automated Maven Release"
      - name: Publish the release
        run: sbt "release with-defaults"