name: Compatibility Report
on:
  workflow_dispatch:
  pull_request:

jobs:
  add_compatibility_report_to_pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add Compatibility Report
        run: ./update_pr_with_compatibility_info.sh "$PR_NUMBER"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
